version: '3.5'

services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    ports:
      - 18083:18083
      - 1883:1883
      - 8083:8083
      - 8081:8081
    volumes:
      - ./data:/opt/emqx/data
      - ./log:/opt/emqx/log
      - ./etc:/opt/emqx/etc
    restart: always